User.create!(display_name: "Dany Stormborn",
    alternate_name: "Danielle Cushing",
    email: "dcushing09@gmail.com",
    password: "2$u4dWm1",
    password_confirmation: "2$u4dWm1",
    admin: true,
    activated: true,
    activated_at: Time.zone.now,
    league: "Seacoast Roller Derby",
    blocker: true,
    jammer: true,
    freshmeat: false,
    ref: true,
    nso: true)